baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Personal website of Lo誰c Davadan"
theme = "hugo-lamp"
googleAnalytics = ""          # Google Analytics UA number

[params]
  subtitle = "Personal website for my internship"
  author = "Lo誰c Davadan"
  logo = ""
  description = "This website was developed as a logbook to keep tracks fof my work"
  paginate = 10

  # Publisher
  ## adsensePublisher = ""    # Required if you want to include Google Adsense
  adsenseSlot = ""                   # Required slot to display ads
  adsenseSlotSticky = ""             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

  # SEO configs
  seotitle = "Personal website of Lo誰c Davadan (SEO Version)"
  googleSiteVerification = ""    # Google Webmaster
  msValidate = ""                  # Bing Webmaster

  # Social networks
  email = "loic.davadan@agro-bordeaux.fr"
  github = "https://github.com/ldavadan"
  linkedin = "www.linkedin.com/in/lo誰c-davadan-886b00145"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Posts"
  weight = 1
  identifier = "posts"
  url = "/posts/"
[[menu.main]]
  name = "About"
  weight = 2
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Tags"
  weight = 3
  identifier = "tags"
  url = "/tags/"
